In [1]:
# 2. Create NumPy Arrays
import numpy as np

arr = np.array([10, 20, 30, 40])
print(arr)
print(type(arr))


[10 20 30 40]
<class 'numpy.ndarray'>


In [13]:
# Multi-Dimensional Array
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)
print(matrix[0], matrix[1])

for i in matrix:
    for j in i:
        print(j)


[[1 2 3]
 [4 5 6]]
[1 2 3] [4 5 6]
1
2
3
4
5
6


In [ ]:
# 3. Shape, Size, Dimensions
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6]])

print(matrix.shape)   # rows, cols
print(matrix.size)    # total elements
print(matrix.ndim)    # dimension count
print(matrix.dtype)   # data type


(2, 3)
6
2
int64


In [19]:
# 4. Indexing & Slicing
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr[1], arr[-1], arr[1:3])

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix[0])
print(matrix[0][1])


2 5 [2 3]
[1 2 3]
2


In [31]:
# 5. Creating Data Fast
import numpy as np

print(np.zeros((3,3)))  # Creates a 3x3 zero matrix
print(np.ones((2,3)))   # Creates a 2x3 ones matrix
print(np.arange(1,10))    # Generate a range from 1-10 (10 not included)
print(np.linspace(1,100,5)) # Generates 5 equally spaced numbers between 1 & 100
print(np.random.randint(1,50,10))   # List of 10 random numbers, range(1-50)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 2 3 4 5 6 7 8 9]
[  1.    25.75  50.5   75.25 100.  ]
[39 30 18 30 24 31 21 18 44 42]


In [33]:
# 6. Mathematical Operations (Power of NumPy)

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(f"a = {a}, b = {b}")
print(f"a + b = {a + b}")
print(f'a x b = {a * b}')
print(f'a ^ 2 = {a ** 2}')


a = [10 20 30], b = [1 2 3]
a + b = [11 22 33]
a x b = [10 40 90]
a ^ 2 = [100 400 900]


In [36]:
# 7. NumPy Functions
a = np.array([12, 45, 2, 89, 67])

print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.sum(a))
print(round(np.std(a), 2))


2
89
43.0
215
32.67


In [37]:
# 8. Boolean Filtering
arr = np.array([12, 45, 2, 89, 67])
print(arr[arr > 40])


[45 89 67]


In [ ]:
# 🧠 Task 1 - Create a Student Score Array
# Create NumPy array of marks for 5 students (math scores): [56, 78, 90, 45, 88]

# Find:
# ✅ Highest
# ✅ Lowest
# ✅ Average
# ✅ Standard Deviation

scores = np.array([56, 78, 90, 45, 88])

print(f'Highest score: {np.max(scores)}')
print(f'Lowest score: {np.min(scores)}')
print(f'Average score: {np.mean(scores)}')
print(f'Standard Deviation: {round(np.std(scores), 2)}')


Highest score: 90
Lowest score: 45
Average score: 71.4
Standard Deviation: 17.88


In [41]:
# 🧠 Task 2 — Generate Random Employee Salaries
# Generate: 10 salaries between 20000–70000
# Filter:
# ✅ Salaries greater than 50000
# ✅ Count how many

sals = np.random.randint(20000, 70000, 10)

print(f'Salaries: {sals}')
print(f'Salaries greater than 50000: {sals[sals > 50000]}')
print(f'How many? {len(sals)}')


Salaries: [62201 38172 69888 38521 40977 47759 52088 24157 51904 45419]
Salaries greater than 50000: [62201 69888 52088 51904]
How many? 10


In [43]:
# 🧠 Task 3 — Matrix Task
# Create a 3x3 matrix of: 1 to 9
# Find:
# ✅ Transpose
# ✅ Row sums
# ✅ Column sums

matrix = np.arange(1, 10).reshape(3, 3)
print(f'3x3 matrix: \n{matrix}')
print(f'\nTranspose: \n{matrix.T}')

row_sums = []
for i in matrix:
    row_sums.append(int(np.sum(i)))
print(f'\nRow sums: {row_sums}')

col_sums = []
sum = 0
for i in matrix.T:
    col_sums.append(int(np.sum(i)))
print(f'\nColumn sums: {col_sums}')


3x3 matrix: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Row sums: [6, 15, 24]

Column sums: [12, 15, 18]


In [47]:
# 🧠 Task 4 — Mini Project: Score Analysis
# Given: scores = [35, 78, 90, 45, 60, 88, 92, 50]
# Find:
# ✅ All passed (>=50)
# ✅ Count failed
# ✅ Highest scorer
# ✅ Class average

scores = np.array([35, 78, 90, 45, 60, 88, 92, 50])

print(f'All passed: {scores[scores >= 50]}')
print(f'Failed: {scores[scores < 50]}')
print(f'Highest score: {np.max(scores)}')
print(f'Class average: {round(np.mean(scores), 1)}')


All passed: [78 90 60 88 92 50]
Failed: [35 45]
Highest score: 92
Class average: 67.2
